Forum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('forumapp.urls', namespace="forumapp")),
    url(r'^api/', include('df2.urls', namespace='drf')),

    url(r'^accounts/logout/$', logout),
]

df2/urls.py
from django.contrib.auth.decorators import login_required

__author__ = 'discovery'


from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from df2 import views



router = DefaultRouter()
router.register('categories', views.CategoriesViewset, base_name='categories')
router.register(r'posts', views.TopicsViewset,base_name='post')
router.register(r'comments',views.CommentViewset)
router.register(r'users',views.UserViewset)



urlpatterns = [
    url(r'^', (include(router.get_urls()))),
    url(r'^like/(?P<question_id>\d+)/$', (views.LikeView.as_view()), name="like"),
    url(r'^login/$', (views.loginView.as_view()), name="login"),
    url(r'^logout/$', (views.logOutView.as_view()), name="logout"),
    url(r'^auth/$',
        views.AuthView.as_view(),
        name='authenticate')

]

forumapp/urls.py
__author__ = 'discovery'
__author__ = 'discovery'
from django.conf.urls import url
from django.contrib.auth.views import login, logout


from django.conf.urls import url



from . import views

# all url patterns
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$',views.VoteView.as_view(), name='vote'),
    url(r'^categories/$', views.CategoriesView.as_view(), name='categories'),
    url(r'^topic/(?P<question_id>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^comment/$', views.CommentView.as_view(), name='comment'),
    url(r'^update/(?P<question_id>\d+)/$', views.CategoriesUpdateView.as_view(), name='updatecat'),
    url(r'^delete/(?P<id>\d+)/$',views.delete,name='deletecat'),



    #url(r'^(?P<pk>[0-9]+)/vote/$', views.VotesView.as_view(), name='vote'),
]

forumapp/models.py
from django.db import models

# Create your models here.
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
# class User2(models.Model):
#     #user_id =models.PositiveIntegerField(verbose_name="User ID")
#     user_name = models.CharField(verbose_name="User Name", max_length=500)
#     user_pass = models.CharField(verbose_name="Password", max_length=500)
#     user_mail = models.EmailField(verbose_name="E-Mail", max_length=500)
#     user_date = models.DateTimeField("Publish Date", auto_now_add=True)
#
#     def __str__(self):
#         return self.user_name

#Question models it has a name and date
class Categories(models.Model):
    #user = models.ForeignKey(User)
    #cat_id =models.PositiveIntegerField(verbose_name="Cat ID")
    cat_name = models.CharField(verbose_name="Categories", max_length=500)
    cat_description = models.CharField(verbose_name="Categories Description", max_length=1500)
    pub_date = models.DateTimeField("Publish Date", auto_now_add=True)

    # this method get us Quesiton class name
    def __str__(self):
        return self.cat_name
    #property means call method like a variable
    #@property
    #def was_published_recently(self):
    #    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# Choice model it has a question relational , choice name and votes number
class Topics(models.Model):
    user = models.ForeignKey(User)
    categories = models.ForeignKey(Categories)
    #topic_id =models.PositiveIntegerField(verbose_name="Topic ID")
    topic_subject = models.CharField(verbose_name="Topic Subject", max_length=1500)
    topic_date = models.DateTimeField("Publish Date", auto_now_add=True)
    #topic_cat =models.PositiveIntegerField(verbose_name="Topic Cat")
    #topic_by =models.PositiveIntegerField(verbose_name="Topic By")
    like = models.IntegerField(verbose_name='Like',default=0)

    # this method get us Quesiton class name
    def __str__(self):
        return self.topic_subject


class Posts(models.Model):
    user = models.ForeignKey(User)
    topics = models.ForeignKey(Topics)
    #posts_id =models.PositiveIntegerField(verbose_name="Post ID")
    posts_content = models.CharField(verbose_name="Post Content", max_length=500)
    posts_date = models.DateTimeField("Post Date", auto_now_add=True)
    #posts_topic =models.PositiveIntegerField(verbose_name="Post Cat")
    #posts_by =models.PositiveIntegerField(verbose_name="Post By")

class Comment(models.Model):
    user= models.ForeignKey(User)
    topics=models.ForeignKey(Topics)
    comment= models.CharField(verbose_name="Comment ",max_length=500)
    comment_date= models.DateTimeField("Comment Date", auto_now_add=True)

    # this method get us Quesiton class name



    #unicode is same _str_
    def __unicode__(self):
        return self.comment

forumapp/forms.py
__author__ = 'discovery'
__author__ = 'discovery'
from django import forms

from forumapp.models import Categories, Topics,Comment
from django.contrib.auth.models import User


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        #form for questions text box date is auto
        fields = ['cat_name','cat_description']



class TopicsForm(forms.ModelForm):
    class Meta:
        model = Topics
        #form for choice
        fields = ['categories', 'topic_subject']

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class CategoriesUpdateForm(forms.ModelForm):
    class meta:
        model = Categories
        fields = ['cat_name','cat_description']

forumapp/views.py
import profile
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404

# Create your views here.
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.views import generic
from django.views.generic import View
from django.contrib import auth
from forumapp.forms import CategoriesForm, TopicsForm,CommentsForm
from forumapp.models import Categories, Topics
from django.contrib.auth.models import User

from django.contrib.auth.models import User
from django import forms



class IndexView(generic.ListView):

    model = Categories
    template_name = 'index.html'
    context_object_name = 'latest_categories_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Categories.objects.order_by('pub_date')


class DetailView(generic.DetailView):
    model = Categories
    template_name = 'category.html'
    comment_form=CommentsForm()





#Results view class for votes results
class ResultsView(generic.DetailView):
    model = Categories
    template_name = 'results.html'


# Question view for list all of Questions
class CategoriesView(View):
    # get method 
    def get(self, request):
        categories_form = CategoriesForm()
        return render(request, 'create_cat.html', {
            'categories_form': categories_form,
        })

    def post(self, request):
        categories_form = CategoriesForm(request.POST)
        if categories_form.is_valid():
            categories_form.save()
            return HttpResponseRedirect(reverse('forumapp:index'))
        else:
            return render(request, 'create_cat.html', {
                'categories_form': categories_form,
                'errors': categories_form.errors
            })
class CategoriesUpdateView(View):

    def dispatch(self, request, question_id, *args, **kwargs):
        self.categories = Categories.objects.get(pk=question_id)
        return super(CategoriesUpdateView, self).dispatch(request, *args, **kwargs)
    def get(self, request):

        self.categories_form = CategoriesForm()
        return render(request, 'updateCat.html', {
            'categories_form': self.categories_form,
        })

    def post(self, request):
        self.categories_form = CategoriesForm(request.POST)
        if self.categories_form.is_valid():
            self.categories.delete()
            self.categories_form.save()
            return HttpResponseRedirect(reverse('forumapp:index'))
        else:
            return render(request, 'create_cat.html', {
                'categories_form': self.categories_form,
                'errors': self.categories_form.errors
            })
def delete(request, id):
    categories = get_object_or_404(Categories, pk=id).delete()
    return HttpResponseRedirect(reverse('forumapp:index'))


#Choice view for create a new choice
class TopicView(View):
    # get and post same part
    def dispatch(self, request, question_id, *args, **kwargs):
        self.categories = Categories.objects.get(pk=question_id)
        return super(TopicView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        choice_form = TopicsForm(initial={'categories': self.categories})
        return render(request, 'create_topic.html', {
            'categories': self.categories,
            'choice_form': choice_form,
        })

    def post(self, request, *args, **kwargs):
        choice_form = TopicsForm(request.POST, initial={'categories': self.categories})
        if choice_form.is_valid():
            choice_form.save()
            return HttpResponseRedirect(reverse('forumapp:detail', args=(choice_form.cleaned_data.get('categories').pk,)))
        else:
            return render(request, 'create_topic.html', {
                'categories': self.categories,
                'choice_form': choice_form,
                'errors': choice_form.errors
            })


class CommentView(View):
    # get and post same part
    # get method
    def get(self, request):
        comments_form = CommentsForm()
        return render(request, 'comment.html', {
            'comments_form': comments_form,
        })

    def post(self, request):
        comments_form = CommentsForm(request.POST)
        if comments_form.is_valid():
            comments_form.save()
            return HttpResponseRedirect(reverse('forumapp:index'))
        else:
            return render(request, 'comment.html', {
                'comments_form': comments_form,
                'errors': comments_form.errors
            })



def login_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        # Correct password, and the user is marked "active"
        auth.login(request, user)
        # Redirect to a success page.
        return HttpResponseRedirect(reverse("login"))
    else:
        # Show an error page
        return HttpResponseRedirect("/account/invalid/")

def logout_view(request):
    auth.logout(request)
    # Redirect to a success page.
    if request.method =='POST':
        return render("index.html")


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/books/")
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {
        'form': form,
    })

forumapp/templates/category.html
  {% include "polls/../../../../Forum/forumapp/templates/import.html" %}
    {% if request.user.is_authenticated %}

    <a href="{% url 'forumapp:topic' categories.pk %}">Create Post</a>
        <a  style="display: inline-block" href="{% url 'forumapp:updatecat' categories.pk%}">Update Category </a>
        <a  style="display: inline-block" href="{% url 'forumapp:deletecat' categories.pk%}">Delete Category </a>
        <a  style="display: inline-block" href="{% url 'forumapp:comment'%}">Comment Category </a>
    {% endif %}
    <h2>{{ categories.cat_name }}</h2>
    <p>  <br/><br/>

    </p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for choice in categories.topics_set.all %}
        {{ choice.topic_subject }} {{ choice.topic_date }}<br/>
        {% for choice2 in request.user.ldap_user.comments_set.all %}
             <h3>{{ choice2.comment }} {{ choice2.user.user_name }}</h3>



        {% endfor %}

        <br/><br/>
    {% endfor %}



    </form>


 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/comment.html
{% include "polls/../../../../Forum/forumapp/templates/import.html" %}

    <h2 style="font-family:Arial">Add a comment</h2>

  {% if errors %}
        {% for key,error in errors.iteritems %}
          {{ key }}: {{ error }}
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}

        <div style="color: #009FC1" >
          <label for="topic_subject">Topics</label>
          {{ comments_form.topics }}
        </div></br></br>
        <div style="color: #032472">
          <label for="topic_subject">Comments</label>
          {{ comments_form.comment }}
        </div></br>
        <div >
            <input style="background-color: #dddbd7 ;font-size: larger ; color: #B40E1F"  type="submit" value="Save"/>
        </div></br>

      </form>

 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/create_cat.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}

<h2 style="font-family: Arial">Add a Category</h2>



  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="cat_name"></label>
        <h3>Category Name</h3>
        {{ categories_form.cat_name }}
        <h3>Category Description</h3>
        {{ categories_form.cat_description }}<br/><br/>

    <input type="submit" value="Save"/>
  </form>

 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/create_topic.html
{% include "polls/../../../../Forum/forumapp/templates/import.html" %}

    <h2 style="font-family:Arial">Add a Topic</h2>

  {% if errors %}
        {% for key,error in errors.iteritems %}
          {{ key }}: {{ error }}
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}

        <div style="color: #009FC1" >
          <label for="cat_name">Categories</label>
          {{ choice_form.categories }}
        </div></br></br>
        <div style="color: #032472">
          <label for="cat_name">Topic</label>
          {{ choice_form.topic_subject }}
        </div></br>
        <div >
            <input style="background-color: #dddbd7 ;font-size: larger ; color: #B40E1F"  type="submit" value="Save"/>
        </div></br>

      </form>

 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/downPage.html
<!DOCTYPE html>


    </br></br><div align="buttom" style="font-family: Arial">
        &copy; Her Hakkı Saklıdır EGEMSOFT
    </div>
</div>

</body>

forumapp/templates/footer.html
<div id="footer">Copyrihts@</div>
</body>
</html>

forumapp/templates/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="nl" lang="nl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="A short description." />
	<meta name="keywords" content="put, keywords, here" />
	<title>G.T.U Forum</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
	<link rel="stylesheet" href="css/menu.css" type="text/css">
    <script src="js/jquery.min.js"></script>
    <script src="js/jquery.form-validator.min.js"></script>
</head>
<body>


	<div id="wrapper">
	
	<div id="logo">
	<table style="width:200px; float:left; ">
	<tr>
	<td><img  src="img/logo.png"  height="40" width="200"></td>
	<td><h1 style="float:left;">G.T.U</h1></td>
	</tr>
	</table>
	</div>
	
	<div id="menu">
	
		<ul class="menuTemplate3 decor3_1" license="mylicense">
		<li><a href="/forum/index.php">Home</a></li>
			<li class="separator"></li>
		<li><a href="/forum/create_topic.php">Create a topic</a></li>
					<li class="separator"></li>
		<li><a href="/forum/create_cat.php">Create a category</a></li>
		
		<div id="userbar">	
		<?php
 session_start();
 if(isset($_SESSION['signed_in'])){
   echo '<li style="margin-top:10px;">Welcome, ' . $_SESSION['user_name'] . '</li>. <li><a style="text-decoration: underline;" href="signout.php">Log Out</a></li>.';

	 
	 	}
 	else
 	{
 		echo '<li><a href="signin.php">Log In</a></li> <li class="separator"></li> <li><a href="signup.php">Create an account</a></li>.';
 	}
?>

		</div>
		</ul>

	

		

</div>
		<div id="content">
	

forumapp/templates/import.html
<title>EgemSoft Blog</title>

<body style="background-color: gray">
<div align="center">

    {% if request.user.is_authenticated %}


        <a  style="display: inline-block" href="{% url 'forumapp:index' %}">Home Page   </a> || <a style="display: inline-block" href="{% url 'forumapp:categories' %}">   Create Category</a>   <div align="right"><a href="accounts/logout">Hi {{ request.user.username }}    Log Out </a></div>



    {% else %}
        <a href="accounts/login">log in </a>


    {% endif %}

forumapp/templates/index.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}


<div style="color: #009FC1">
    <h1 xmlns="http://www.w3.org/1999/html" style="font-family: Verdana">Welcome  My Blog </h1>
    <h2>Lets Begin </h2>
</div></br></br>


{% if latest_categories_list %}
    <ul>
    {% for category in latest_categories_list %}
        <h2>Category Name       :<a href="/{{ category.id }}/">    {{ category.cat_name }}</a></h2></br><br/>
                Category Description: {{ category.cat_description }}<br/><br/>
                 Category Date: {{ category.pub_date }}<br/>

        {% if category.topics_set.all%}
        <h3>{{ category.cat_name }}  Posts </h3>
        {% for choice in category.topics_set.all %}
            <li>{{ choice.topic_subject }}</li>


        {% endfor %}</br></br>
        {% else %}
            No Post Posted</br></br>
        {%endif%}

    {% endfor %}
    </ul>

{% else %}

    <p>No Categories Posted Yet.</p>
{% endif %}


 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/login.html
{% block content %}

  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}

  <form action="" method="post">
    <label for="username">User name:</label>
    <input type="text" name="username" value="" id="username">
    <label for="password">Password:</label>
    <input type="password" name="password" value="" id="password">

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next|escape }}" />
  </form>

{% endblock %}

forumapp/templates/replyon.html
<?php
//create_cat.php
include 'connect.php';

include 'header.php';

if($_SERVER['REQUEST_METHOD'] != 'POST')
{
	//someone is calling the file directly, which we don't want
	echo 'This file cannot be called directly.';
}
else
{
	//check for sign in status
	if(!$_SESSION['signed_in'])
	{
		echo 'You must be signed in to post a reply.';
	}
	else
	{
		//a real user posted a real reply
		$sql = "INSERT INTO 
					posts(post_content,
						  post_date,
						  post_topic,
						  post_by) 
				VALUES ('" . $_POST['reply-content'] . "',
						NOW(),
						" . $con->real_escape_string($_GET['id']) . ",
						" . $_SESSION['user_id'] . ")";
						
		$result = $con->query($sql);
						
		if(!$result)
		{
			echo 'Your reply has not been saved, please try again later.';
		}
		else
		{
			echo 'Your reply has been saved, check out <a href="topic.php?id=' . htmlentities($_GET['id']) . '">the topic</a>.';
		}
	}
}

include 'footer.php';
?>

forumapp/templates/updateCat.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}

<h2 style="font-family: Arial">Update a Category</h2>



  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="cat_name"></label>
        <h3>Category Name</h3>
        {{ categories_form.cat_name }}
        <h3>Category Description</h3>
        {{ categories_form.cat_description }}<br/><br/>

    <input type="submit" value="Save"/>
  </form>

 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

forumapp/templates/updateTopic.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>